### ISSUE TITLE
Show dot-folders?

### ISSUE THREAD

**Issue by VKondakoff** [Zane-/cder.nvim#3]
Hi!

Thanks for an useful plugin! There is a question, though: is there a way to show dot-folders (like '.config' or '.local') in the folders list? I have added the following line in Telescope extensions config, but the dot-folders are still not in the list:

```
    cder = {
      dir_command = { 'fd', '--hidden', '--type=d', '.', os.getenv('HOME') },
      -- command_executer = { 'zsh', '-c' },
    },
```

Thanks again!

**Comment by Zane-** [comment]
Does `-HI` instead of `--hidden` work?

**Comment by VKondakoff** [comment]
No:
<img width="846" alt="Снимок экрана 2022-06-25 в 23 20 42" src="https://user-images.githubusercontent.com/230824/175789415-c49372f5-8958-4469-a5f0-d2c720cf744a.png">
(macOS Monterey 12.4)

**Comment by Zane-** [comment]
Hmm, well I guess you should try to find a command that works for you, this plugin just displays whatever the dir_command returns, so you can experiment in your terminal until you find the right flags and directory to use
