### ISSUE TITLE
Replace os.getenv('HOME') with vim.uv.os_homedir()

### ISSUE THREAD

**Issue by thiru** [Zane-/cder.nvim#8]
The HOME environment variable isn't set by default in Windows.  If you replace calls to `os.getenv('HOME')` with `vim.uv.os_homedir()` it will work more reliably across all platforms.  Happy to create a PR if you'd like.

**Comment by Zane-** [comment]
Done: https://github.com/Zane-/cder.nvim/commit/0a071389bb52544ac9cf9557378aa1212dff6982
